---
title: "Lesson 10: Modelling Spatial Interaction: Huff and MCI Models"
date: "November 3, 2025"
date-modified: "last-modified"
output:
  html:
    toc: true
    toc_depth: 3
execute: 
  freeze: true
---

In this lesson, you will learn the basic concepts Spatial Interaction and Huff and MCI Models for market area analysis.

## Content

-   Basic Concepts of Spatial Interaction
-   Introducing Huff model
    -   Basic concepts and method
    -   Calibrating Huff model
    -   Interpreting Huff model results
-   Introducing Multiplicative Competitive Interaction Model (MCI)
    -   Basic concepts and method
    -   Calibrating MCI model
    -   Interpreting MCI model results

## Lesson Slides and Hands-on Notes

-   Lesson 10 slides in [html](../lesson/Lesson10/Lesson10-Huff.html) format.

## Self-reading Before Meet-up

Read before lesson:

-   [A.18 – Spatial Interactions and the Gravity Model](https://transportgeography.org/contents/methods/spatial-interactions-gravity-model/)
-   [A.15 – Market Area Analysis](https://transportgeography.org/contents/methods/market-area-analysis/)
-   Huff, D. (1963)[A Probabilistic Analysis of Shopping Center Trade Areas](https://www.jstor.org/stable/3144521)
-   Masao Nakanishi, Lee G. Cooper, (1982) [Technical Note—Simplified Estimation Procedures for MCI Models](https://www.anderson.ucla.edu/faculty/lee.cooper/Pubs/Simplified%20Estimation%20for%20MCI%20Models.pdf). Marketing Science 1(3):314-322. http://dx.doi.org/10.1287/mksc.1.3.314

## Reference

-   Kingsley E. Haynes and A. Stewart Fotheringham (2020) [**Gravity and Spatial Interaction Models**](https://researchrepository.wvu.edu/rri-web-book/16/), Web Book of Regional Science. Chapter 1 and Sub-section 2.2.
-   Farmer, C. and Oshan, T. (2017). ["Spatial interaction"](https://gistbok.ucgis.org/bok-topics/spatial-interaction). **The Geographic Information Science & Technology Body of Knowledge** (4th Quarter 2017 Edition), John P. Wilson (ed.). DOI: 10.22224/gistbok/2017.4.5 (link is external)
-   Flowerdew R, Aitkin M (1982) ["A method of fitting the gravity model based on the Poisson distribution"](https://www.academia.edu/38321611/A_Method_of_Fitting_the_Gravity_Model_Based_on_the_Poisson_Distribution_). *Journal of Regional Science*, 22: 191--202.
-   [" Chapter 6. Spatial econometrics - common models"](https://www.insee.fr/en/statistiques/fichier/3635545/imet131-j-chapitre-6.pdf), Handbook of Spatial Analysis.
-   James P. LeSage and R. Kelley Pace (2008) ["Spatial Econometric Modeling of Origin-Destination Flows"](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1467-9787.2008.00573.x). *Journal of Regional Science*, Vol. 48, No. 5, pp. 941-967.
-   Pavel KLAPKA, et. al. (2013) ["The Footfall of Shopping Centre in Olomouc (CZECH REPUBLIC): An Application of The Gravity Model"](https://sciendo.com/de/article/10.2478/mgr-2013-0013), *Moravian Geographical Reports*, Vol 21, pp. 12-26.\
-   Yang Yue et. al. (2012) "Exploratory calibration of a spatial interaction model using taxi GPS trajectories", *Computers, Environment and Urban Systems*, 36 (2012) 140--153.
-   Morito Tsutsumi and Kazuki Tamesue (2012) "Intraregional flow problem in spatial econometric model for origin-destination flows", *Environment and Planning B: Planning and Design*, Vol. 39, pp. 1006-1015. Access via SMU e-journal.

## All About R:

-   [MCI: Multiplicative Competitive Interaction (MCI) Model](https://cran.r-project.org/web/packages/MCI/index.html)
-   Wieland, T., (2017) [Market Area Analysis for Retail and Service Locations with MCI](https://journal.r-project.org/articles/RJ-2017-020/RJ-2017-020.pdf), The R Journal, Vol. 9, No. 1, pp. 298-323.
-   [REAT: Regional Economic Analysis Toolbox](https://cran.r-project.org/web/packages/REAT/index.html)
